// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/_middleware.ts";
import * as $1 from "./routes/configure.tsx";
import * as $2 from "./routes/index.tsx";
import * as $3 from "./routes/share.ts";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $0,
    "./routes/configure.tsx": $1,
    "./routes/index.tsx": $2,
    "./routes/share.ts": $3,
  },
  islands: {},
  baseUrl: import.meta.url,
  config,
};

export default manifest;
