// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $configure_elk from "./routes/configure/elk.ts";
import * as $configure_index from "./routes/configure/index.tsx";
import * as $index from "./routes/index.tsx";
import * as $share from "./routes/share.ts";

import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/configure/elk.ts": $configure_elk,
    "./routes/configure/index.tsx": $configure_index,
    "./routes/index.tsx": $index,
    "./routes/share.ts": $share,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
